"""added a verification status field to user model

Revision ID: 1722491029bf
Revises: e42f2f3fd6f7
Create Date: 2022-05-21 09:50:53.847320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1722491029bf'
down_revision = 'e42f2f3fd6f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id_ver_status', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'id_ver_status')
    # ### end Alembic commands ###
