"""added verification fields

Revision ID: 4170c0352520
Revises: 
Create Date: 2022-05-02 13:20:09.701329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4170c0352520'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_email_verified', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_number_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_number_verified')
    op.drop_column('user', 'is_email_verified')
    # ### end Alembic commands ###
