"""added a field for image verification

Revision ID: 49092dba9ecf
Revises: 4f9a4c080204
Create Date: 2022-06-14 18:27:09.316859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49092dba9ecf'
down_revision = '4f9a4c080204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_link_for_verification', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image_link_for_verification')
    # ### end Alembic commands ###
