"""self referential table for close contacts of users

Revision ID: 561dff7e0ed5
Revises: 4170c0352520
Create Date: 2022-05-05 21:57:30.448778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '561dff7e0ed5'
down_revision = '4170c0352520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('known_by',
    sa.Column('knows_id', sa.Integer(), nullable=True),
    sa.Column('known_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['known_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['knows_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('known_by')
    # ### end Alembic commands ###
