"""added verification request table

Revision ID: 883fa35d524a
Revises: acc6ae83fa54
Create Date: 2022-05-21 10:18:02.026727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '883fa35d524a'
down_revision = 'acc6ae83fa54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification')
    # ### end Alembic commands ###
