"""changed data type of verification field

Revision ID: acc6ae83fa54
Revises: 1722491029bf
Create Date: 2022-05-21 10:01:25.089016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acc6ae83fa54'
down_revision = '1722491029bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id_being_verified', sa.Boolean(), nullable=True))
    op.drop_column('user', 'id_ver_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id_ver_status', sa.VARCHAR(length=3), nullable=True))
    op.drop_column('user', 'id_being_verified')
    # ### end Alembic commands ###
