"""renamed column in visited table

Revision ID: dff406f6e400
Revises: 8aa6e11347b2
Create Date: 2022-06-15 20:54:10.391931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dff406f6e400'
down_revision = '8aa6e11347b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visited', sa.Column('date_visited', sa.DateTime(), nullable=True))
    op.drop_column('visited', 'date_tested')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visited', sa.Column('date_tested', sa.DATETIME(), nullable=True))
    op.drop_column('visited', 'date_visited')
    # ### end Alembic commands ###
