"""added other names column

Revision ID: e42f2f3fd6f7
Revises: 561dff7e0ed5
Create Date: 2022-05-14 14:42:18.780509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e42f2f3fd6f7'
down_revision = '561dff7e0ed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('other_names', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'other_names')
    # ### end Alembic commands ###
